/** Modern curated category color palette (Material 3 Expressive) */
export const CATEGORY_COLORS = [
  { hex: '#e07a5f', name: 'Coral' },
  { hex: '#ff6e42', name: 'Vibrant Coral' },
  { hex: '#3d5a80', name: 'Ocean Blue' },
  { hex: '#678ec9', name: 'Periwinkle' },
  { hex: '#21a7cf', name: 'Azure' },
  { hex: '#81b29a', name: 'Sage Green' },
  { hex: '#2a9d8f', name: 'Emerald' },
  { hex: '#ffe28d', name: 'Champagne Gold' },
  { hex: '#f2cc8f', name: 'Warm Amber' },
  { hex: '#fedfcb', name: 'Peach' },
  { hex: '#ffcee3', name: 'Soft Pink' },
  { hex: '#9b5de5', name: 'Royal Purple' },
  { hex: '#391a77', name: 'Deep Violet' },
  { hex: '#ef476f', name: 'Rose Red' },
  { hex: '#118ab2', name: 'Deep Teal' },
  { hex: '#073b4c', name: 'Midnight' },
  { hex: '#092634', name: 'Navy Blue' },
  { hex: '#6c757d', name: 'Slate Gray' },
] as const
