<script setup lang="ts">
import {
  Activity,
  Apple,
  Award,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Calculator,
  Camera,
  Car,
  ChartPie,
  Circle,
  CircleEllipsis,
  Clapperboard,
  Cloud,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CreditCard,
  Cross,
  DollarSign,
  Droplets,
  Dumbbell,
  FileText,
  Film,
  Flower2,
  Folder,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GlassWater,
  GraduationCap,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Key,
  Landmark,
  Laptop,
  Luggage,
  MapPin,
  Mic,
  Music,
  Navigation,
  Package,
  Palette,
  Palmtree,
  PawPrint,
  PenTool,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  PlusCircle,
  Receipt,
  Repeat,
  Sandwich,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Syringe,
  Tag,
  Target,
  Tent,
  Ticket,
  Train,
  TreePine,
  TrendingDown,
  TrendingUp,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  Vault,
  Wallet,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from '@lucide/vue'
import { computed, type Component } from 'vue'

const props = withDefaults(
  defineProps<{
    name: string
    size?: number
  }>(),
  { size: 20 },
)

const map: Record<string, Component> = {
  // Food & Drinks
  utensils: Utensils,
  coffee: Coffee,
  beer: Beer,
  pizza: Pizza,
  apple: Apple,
  cake: Cake,
  'glass-water': GlassWater,
  wine: Wine,
  sandwich: Sandwich,
  cookie: Cookie,

  // Transportation & Travel
  car: Car,
  bus: Bus,
  fuel: Fuel,
  plane: Plane,
  bike: Bike,
  train: Train,
  navigation: Navigation,
  compass: Compass,
  'map-pin': MapPin,
  ticket: Ticket,
  luggage: Luggage,

  // Shopping & Retail
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  shirt: Shirt,
  store: Store,
  package: Package,
  scissors: Scissors,
  watch: Watch,
  gem: Gem,
  footprints: Footprints,
  tag: Tag,

  // Health, Fitness & Beauty
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  activity: Activity,
  sparkles: Sparkles,
  cross: Cross,
  syringe: Syringe,
  brain: Brain,

  // Entertainment & Hobbies
  clapperboard: Clapperboard,
  music: Music,
  'gamepad-2': Gamepad2,
  tv: Tv,
  film: Film,
  camera: Camera,
  headphones: Headphones,
  mic: Mic,
  palette: Palette,

  // Housing, Utilities & Services
  home: Home,
  'building-2': Building2,
  receipt: Receipt,
  zap: Zap,
  droplets: Droplets,
  wifi: Wifi,
  smartphone: Smartphone,
  wrench: Wrench,
  hammer: Hammer,
  plug: Plug,
  key: Key,
  'shield-check': ShieldCheck,

  // Work & Education
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  briefcase: Briefcase,
  laptop: Laptop,
  calculator: Calculator,
  'pen-tool': PenTool,
  'file-text': FileText,
  folder: Folder,
  award: Award,
  target: Target,

  // Finance & Investments
  banknote: Banknote,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  landmark: Landmark,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'dollar-sign': DollarSign,
  coins: Coins,
  vault: Vault,
  'chart-pie': ChartPie,
  'hand-coins': HandCoins,

  // Family, Pets & Life
  baby: Baby,
  'paw-print': PawPrint,
  gift: Gift,
  heart: Heart,
  users: Users,
  user: User,

  // Nature & Outings
  palmtree: Palmtree,
  tent: Tent,
  'tree-pine': TreePine,
  'flower-2': Flower2,
  umbrella: Umbrella,
  cloud: Cloud,

  // Basic
  repeat: Repeat,
  'plus-circle': PlusCircle,
  'circle-ellipsis': CircleEllipsis,
  circle: Circle,
}

const icon = computed(() => map[props.name] ?? Circle)
</script>

<template>
  <component :is="icon" :size="size" />
</template>
